package Clases;
// Generated 25-abr-2013 1:29:18 by Hibernate Tools 3.2.1.GA



/**
 * AuditoriaId generated by hbm2java
 */
public class AuditoriaId  implements java.io.Serializable {


     private int idAuditoria;
     private int idAuditor;

    public AuditoriaId() {
    }

    public AuditoriaId(int idAuditoria, int idAuditor) {
       this.idAuditoria = idAuditoria;
       this.idAuditor = idAuditor;
    }
   
    public int getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(int idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public int getIdAuditor() {
        return this.idAuditor;
    }
    
    public void setIdAuditor(int idAuditor) {
        this.idAuditor = idAuditor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AuditoriaId) ) return false;
		 AuditoriaId castOther = ( AuditoriaId ) other; 
         
		 return (this.getIdAuditoria()==castOther.getIdAuditoria())
 && (this.getIdAuditor()==castOther.getIdAuditor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAuditoria();
         result = 37 * result + this.getIdAuditor();
         return result;
   }   


}


