package Clases;
// Generated 23-may-2013 2:20:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private Integer idAuditoria;
     private Personal personalByIdAuditor;
     private Departamento departamento;
     private Personal personalByIdPersonal;
     private Tarea tarea;
     private Establecimiento establecimiento;
     private Date fecha;
     private String operacion;
     private String campo;
     private String elementoAnterior;
     private String elementoNuevo;

    public Auditoria() {
    }

	
    public Auditoria(Personal personalByIdAuditor, Date fecha, String operacion) {
        this.personalByIdAuditor = personalByIdAuditor;
        this.fecha = fecha;
        this.operacion = operacion;
    }
    public Auditoria(Personal personalByIdAuditor, Departamento departamento, Personal personalByIdPersonal, Tarea tarea, Establecimiento establecimiento, Date fecha, String operacion, String campo, String elementoAnterior, String elementoNuevo) {
       this.personalByIdAuditor = personalByIdAuditor;
       this.departamento = departamento;
       this.personalByIdPersonal = personalByIdPersonal;
       this.tarea = tarea;
       this.establecimiento = establecimiento;
       this.fecha = fecha;
       this.operacion = operacion;
       this.campo = campo;
       this.elementoAnterior = elementoAnterior;
       this.elementoNuevo = elementoNuevo;
    }
    
    @Override
    public String toString() {
        return personalByIdAuditor.getApellido()+" "+personalByIdAuditor.getNombre();
    }
   
    public Integer getIdAuditoria() {
        return this.idAuditoria;
    }
    
    public void setIdAuditoria(Integer idAuditoria) {
        this.idAuditoria = idAuditoria;
    }
    public Personal getPersonalByIdAuditor() {
        return this.personalByIdAuditor;
    }
    
    public void setPersonalByIdAuditor(Personal personalByIdAuditor) {
        this.personalByIdAuditor = personalByIdAuditor;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Personal getPersonalByIdPersonal() {
        return this.personalByIdPersonal;
    }
    
    public void setPersonalByIdPersonal(Personal personalByIdPersonal) {
        this.personalByIdPersonal = personalByIdPersonal;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }
    public String getElementoAnterior() {
        return this.elementoAnterior;
    }
    
    public void setElementoAnterior(String elementoAnterior) {
        this.elementoAnterior = elementoAnterior;
    }
    public String getElementoNuevo() {
        return this.elementoNuevo;
    }
    
    public void setElementoNuevo(String elementoNuevo) {
        this.elementoNuevo = elementoNuevo;
    }

// GENERADO POR GONZALEZ FERNANDO
    
    public void guardarAuditoria(Auditoria unaAuditoria){
        Controlador.getPERSISTENCIA().insert(this);
        //JOptionPane.showMessageDialog(null,"La persona fue registrada correctamente","Registro de Persona",JOptionPane.INFORMATION_MESSAGE);
    }


}


