package Clases;
// Generated 21/02/2013 23:49:41 by Hibernate Tools 3.2.1.GA

import java.util.Iterator;
import javax.swing.JOptionPane;




/**
 * Circularpersonal generated by hbm2java
 */
public class Circularpersonal  implements java.io.Serializable {


     private CircularpersonalId id;
     private Personal personal;
     private Circular circular;
     private String descripcion;

    public Circularpersonal() {
    }

	
    public Circularpersonal(CircularpersonalId id, Personal personal, Circular circular) {
        this.id = id;
        this.personal = personal;
        this.circular = circular;
    }
    public Circularpersonal(CircularpersonalId id, Personal personal, Circular circular, String descripcion) {
       this.id = id;
       this.personal = personal;
       this.circular = circular;
       this.descripcion = descripcion;
    }
    
    @Override
    public String toString() {
        return descripcion;
    }
   
    public CircularpersonalId getId() {
        return this.id;
    }
    
    public void setId(CircularpersonalId id) {
        this.id = id;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Circular getCircular() {
        return this.circular;
    }
    
    public void setCircular(Circular circular) {
        this.circular = circular;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarCircularpersonal(Circularpersonal unCircularpersonal){
        Controlador.getPERSISTENCIA().insert(this);

//        JOptionPane.showMessageDialog(null,"El Departamento se guardó correctamente","Registrar departamento",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void eliminarCircularpersonal(Circularpersonal unCircularpersonal){
//        Iterator it=personalDepartamentos.iterator();
//        if(it.hasNext()){
//            JOptionPane.showMessageDialog(null,"El Departamento no se puede eliminar porque esta relacionada con otros personales","Eliminar departamento",JOptionPane.ERROR_MESSAGE);
//        }else{
        Controlador.getPERSISTENCIA().delete(this);
//        JOptionPane.showMessageDialog(null,"El Departamento se eliminó correctamente","Eliminar departamento",JOptionPane.INFORMATION_MESSAGE);
//        }
    }


}


