package Clases;
// Generated 04/12/2012 09:56:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Iniciofin generated by hbm2java
 */
public class Iniciofin  implements java.io.Serializable {


     private Integer idIniciofin;
     private Dia dia;
     private Date inicio;
     private Boolean estadoInicio;
     private Date fin;
     private Boolean estadoFin;
     private Set<Asistencia> asistencias = new HashSet<Asistencia>(0);

    public Iniciofin() {
    }

	
    public Iniciofin(Dia dia) {
        this.dia = dia;
    }
    public Iniciofin(Dia dia, Date inicio, Boolean estadoInicio, Date fin, Boolean estadoFin, Set<Asistencia> asistencias) {
       this.dia = dia;
       this.inicio = inicio;
       this.estadoInicio = estadoInicio;
       this.fin = fin;
       this.estadoFin = estadoFin;
       this.asistencias = asistencias;
    }
   
    public Integer getIdIniciofin() {
        return this.idIniciofin;
    }
    
    public void setIdIniciofin(Integer idIniciofin) {
        this.idIniciofin = idIniciofin;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Boolean getEstadoInicio() {
        return this.estadoInicio;
    }
    
    public void setEstadoInicio(Boolean estadoInicio) {
        this.estadoInicio = estadoInicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }
    public Boolean getEstadoFin() {
        return this.estadoFin;
    }
    
    public void setEstadoFin(Boolean estadoFin) {
        this.estadoFin = estadoFin;
    }
    public Set<Asistencia> getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set<Asistencia> asistencias) {
        this.asistencias = asistencias;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarIniciofin(Iniciofin unIniciofin){
        Controlador.getPERSISTENCIA().insert(this);

//        JOptionPane.showMessageDialog(null,"El Iniciofin "+ 
//                String.valueOf(unIniciofin.getIdIniciofin()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarIniciofin(Iniciofin unIniciofin){
        Controlador.getPERSISTENCIA().update(this);

//        JOptionPane.showMessageDialog(null,"El Iniciofin "+ 
//                String.valueOf(unIniciofin.getIdIniciofin()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


