package Clases;
// Generated 25/10/2012 04:33:33 by Hibernate Tools 3.2.1.GA

import javax.swing.JOptionPane;




/**
 * Personalnodocente generated by hbm2java
 */
public class Personalnodocente  implements java.io.Serializable {


     private PersonalnodocenteId id;
     private Personal personal;
     private Actividad actividad;

    public Personalnodocente() {
    }

    public Personalnodocente(PersonalnodocenteId id, Personal personal, Actividad actividad) {
       this.id = id;
       this.personal = personal;
       this.actividad = actividad;
    }
   
    public PersonalnodocenteId getId() {
        return this.id;
    }
    
    public void setId(PersonalnodocenteId id) {
        this.id = id;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }

 //// GENERADO POR GONZALEZ FERNANDO
    
    public void guardarPersonalnodoc(Personalnodocente unPersonalnodoc){
        Controlador.getPERSISTENCIA().insertstring(this);

        JOptionPane.showMessageDialog(null,"El docente "+ 
                String.valueOf(unPersonalnodoc.getId().getIdNodocente()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarPersonalnodoc(Personalnodocente unPersonalnodoc){
        Controlador.getPERSISTENCIA().update(this);

        JOptionPane.showMessageDialog(null,"El docente "+ 
                String.valueOf(unPersonalnodoc.getId().getIdNodocente()) +
                " se actualizó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }

    public void eliminarPersonalnodoc(Personalnodocente unPersonalnodoc){
        Controlador.getPERSISTENCIA().delete(this);

        JOptionPane.showMessageDialog(null,"El docente "+ 
                String.valueOf(unPersonalnodoc.getId().getIdNodocente()) +
                " se elimino correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
}


