package Clases;
// Generated 04/09/2012 11:32:15 by Hibernate Tools 3.2.1.GA



/**
 * PersonalAdministrativos generated by hbm2java
 */
public class PersonalAdministrativos  implements java.io.Serializable {


     private String nroRegistro;
     private Personales personales;
     private String idAdm;
     private String tipodeactividad;
     private String sector;

    public PersonalAdministrativos() {
    }

	
    public PersonalAdministrativos(String nroRegistro, Personales personales) {
        this.nroRegistro = nroRegistro;
        this.personales = personales;
    }
    public PersonalAdministrativos(String nroRegistro, Personales personales, String idAdm, String tipodeactividad, String sector) {
       this.nroRegistro = nroRegistro;
       this.personales = personales;
       this.idAdm = idAdm;
       this.tipodeactividad = tipodeactividad;
       this.sector = sector;
    }
   
    public String getNroRegistro() {
        return this.nroRegistro;
    }
    
    public void setNroRegistro(String nroRegistro) {
        this.nroRegistro = nroRegistro;
    }
    public Personales getPersonales() {
        return this.personales;
    }
    
    public void setPersonales(Personales personales) {
        this.personales = personales;
    }
    public String getIdAdm() {
        return this.idAdm;
    }
    
    public void setIdAdm(String idAdm) {
        this.idAdm = idAdm;
    }
    public String getTipodeactividad() {
        return this.tipodeactividad;
    }
    
    public void setTipodeactividad(String tipodeactividad) {
        this.tipodeactividad = tipodeactividad;
    }
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }


public void guardarAdministrativo(PersonalAdministrativos unAdm) {
        Controlador.getPERSISTENCIA().insert(unAdm);
    }

    public void actualizarAdministrativo(PersonalAdministrativos unAdm) {
        Controlador.getPERSISTENCIA().update(unAdm);
    }

}


