package Clases;
// Generated 02-may-2013 17:40:38 by Hibernate Tools 3.2.1.GA



/**
 * Tareaotro generated by hbm2java
 */
public class Tareaotro  implements java.io.Serializable {


     private TareaotroId id;
     private Tarea tarea;
     private String caracteristica;

    public Tareaotro() {
    }

	
    public Tareaotro(TareaotroId id, Tarea tarea) {
        this.id = id;
        this.tarea = tarea;
    }
    public Tareaotro(TareaotroId id, Tarea tarea, String caracteristica) {
       this.id = id;
       this.tarea = tarea;
       this.caracteristica = caracteristica;
    }
    
//    @Override
//    public String toString() {
//        return tarea.getNombre();
//    }
   
    public TareaotroId getId() {
        return this.id;
    }
    
    public void setId(TareaotroId id) {
        this.id = id;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public String getCaracteristica() {
        return this.caracteristica;
    }
    
    public void setCaracteristica(String caracteristica) {
        this.caracteristica = caracteristica;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarTareaotro(Tareaotro unaTareaotro){
        Controlador.getPERSISTENCIA().insert(this);

//        JOptionPane.showMessageDialog(null,"La Tarea otro "+ 
//                String.valueOf(unaTareaotro.getId()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarTareaotro(Tareaotro unaTareaotro){
        Controlador.getPERSISTENCIA().update(this);

//        JOptionPane.showMessageDialog(null,"La Tarea otro "+ 
//                String.valueOf(unaTareaotro.getId()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


