package Clases;
// Generated 25/10/2012 04:33:33 by Hibernate Tools 3.2.1.GA

import javax.swing.JOptionPane;




/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private Integer idTelefono;
     private Personal personal;
     private String nombre;
     private String numero;

    public Telefono() {
    }

	
    public Telefono(Personal personal) {
        this.personal = personal;
    }
    public Telefono(Personal personal, String nombre, String numero) {
       this.personal = personal;
       this.nombre = nombre;
       this.numero = numero;
    }
    
    @Override
    public String toString() {
        return nombre+" "+numero;
    }
   
    public Integer getIdTelefono() {
        return this.idTelefono;
    }
    
    public void setIdTelefono(Integer idTelefono) {
        this.idTelefono = idTelefono;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarTelefono(Telefono unTelefono){
        Controlador.getPERSISTENCIA().insert(this);

        JOptionPane.showMessageDialog(null,"El Telefono "+ 
                String.valueOf(unTelefono.getIdTelefono()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarTelefono(Telefono unTelefono){
        Controlador.getPERSISTENCIA().saveupdate(this);

        JOptionPane.showMessageDialog(null,"El Telefono "+ 
                String.valueOf(unTelefono.getIdTelefono()) +
                " se actualizó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void eliminarTelefono(Telefono unTelefono){
        Controlador.getPERSISTENCIA().delete(this);

        JOptionPane.showMessageDialog(null,"El Telefono "+ 
                String.valueOf(unTelefono.getIdTelefono()) +
                " se eliminó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


