package Clases;
// Generated 21/02/2013 23:49:41 by Hibernate Tools 3.2.1.GA



/**
 * CircularpersonalId generated by hbm2java
 */
public class CircularpersonalId  implements java.io.Serializable {


     private int idCircular;
     private int idPersonal;

    public CircularpersonalId() {
    }

    public CircularpersonalId(int idCircular, int idPersonal) {
       this.idCircular = idCircular;
       this.idPersonal = idPersonal;
    }
   
    public int getIdCircular() {
        return this.idCircular;
    }
    
    public void setIdCircular(int idCircular) {
        this.idCircular = idCircular;
    }
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CircularpersonalId) ) return false;
		 CircularpersonalId castOther = ( CircularpersonalId ) other; 
         
		 return (this.getIdCircular()==castOther.getIdCircular())
 && (this.getIdPersonal()==castOther.getIdPersonal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCircular();
         result = 37 * result + this.getIdPersonal();
         return result;
   }   


}


