package Clases;
// Generated 18-jun-2013 14:10:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private Anolectivo anolectivo;
     private Establecimiento establecimiento;
     private String nombre;
     private Set<Division> divisions = new HashSet<Division>(0);

    public Curso() {
    }

	
    public Curso(Anolectivo anolectivo, Establecimiento establecimiento) {
        this.anolectivo = anolectivo;
        this.establecimiento = establecimiento;
    }
    public Curso(Anolectivo anolectivo, Establecimiento establecimiento, String nombre, Set<Division> divisions) {
       this.anolectivo = anolectivo;
       this.establecimiento = establecimiento;
       this.nombre = nombre;
       this.divisions = divisions;
    }
    
    @Override
    public String toString() {
        return nombre;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public Anolectivo getAnolectivo() {
        return this.anolectivo;
    }
    
    public void setAnolectivo(Anolectivo anolectivo) {
        this.anolectivo = anolectivo;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Division> getDivisions() {
        return this.divisions;
    }
    
    public void setDivisions(Set<Division> divisions) {
        this.divisions = divisions;
    }

////// GENERADO POR GONZALEZ FERNANDO
    
    public void guardarCurso(Curso unCurso){
        Controlador.getPERSISTENCIA().insert(this);
        JOptionPane.showMessageDialog(null,"El Curso se guardo correctamente","Guardar Curso",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void ActualizarCurso(Curso unCurso){
        Controlador.getPERSISTENCIA().update(this);
        JOptionPane.showMessageDialog(null,"El Curso se actualizó correctamente","Actualizar Curso",JOptionPane.INFORMATION_MESSAGE);
        }
        
    
    public void EliminarCurso(Curso unCurso){
        Iterator it=divisions.iterator();
        if(it.hasNext()){
            JOptionPane.showMessageDialog(null,"El Curso no se puede eliminar porque tiene divisiones","Eliminar Curso",JOptionPane.ERROR_MESSAGE);
        }else{
            Controlador.getPERSISTENCIA().delete(this);
            JOptionPane.showMessageDialog(null,"El Curso se eliminó correctamente","Eliminar Curso",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    


}


