package Clases;
// Generated 18-jun-2013 14:10:38 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Division generated by hbm2java
 */
public class Division  implements java.io.Serializable {


     private Integer idDivision;
     private Curso curso;
     private String nombre;
     private Set<Tarea> tareas = new HashSet<Tarea>(0);

    public Division() {
    }

	
    public Division(Curso curso) {
        this.curso = curso;
    }
    public Division(Curso curso, String nombre, Set<Tarea> tareas) {
       this.curso = curso;
       this.nombre = nombre;
       this.tareas = tareas;
    }
    
    @Override
    public String toString() {
        return nombre;
    }
   
    public Integer getIdDivision() {
        return this.idDivision;
    }
    
    public void setIdDivision(Integer idDivision) {
        this.idDivision = idDivision;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Tarea> getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set<Tarea> tareas) {
        this.tareas = tareas;
    }

////// GENERADO POR GONZALEZ FERNANDO
    
    public void guardarDivision(Division unaDivision){
        Controlador.getPERSISTENCIA().insert(this);
        JOptionPane.showMessageDialog(null,"La Division se guardo correctamente","Guardar Division",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void ActualizarDivision(Division unaDivision){
        Controlador.getPERSISTENCIA().update(this);
        JOptionPane.showMessageDialog(null,"La Division se actualizó correctamente","Actualizar división",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void EliminarDivision(Division unaDivision){
        Iterator it=tareas.iterator();
        if(it.hasNext()){
            JOptionPane.showMessageDialog(null,"La división no se puede eliminar porque tiene clases","Eliminar división",JOptionPane.ERROR_MESSAGE);
        }else{
            Controlador.getPERSISTENCIA().delete(this);
            JOptionPane.showMessageDialog(null,"La Division se eliminó correctamente","Eliminar división",JOptionPane.INFORMATION_MESSAGE);
    
        }
    }

}


