package Clases;
// Generated 31/01/2013 23:17:19 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Feriado generated by hbm2java
 */
public class Feriado  implements java.io.Serializable {


     private Integer idFeriado;
     private Establecimiento establecimiento;
     private String comentario;
     private Date dia;

    public Feriado() {
    }

	
    public Feriado(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public Feriado(Establecimiento establecimiento, String comentario, Date dia) {
       this.establecimiento = establecimiento;
       this.comentario = comentario;
       this.dia = dia;
    }
    
    @Override
    public String toString() {
        return comentario;
    }
   
    public Integer getIdFeriado() {
        return this.idFeriado;
    }
    
    public void setIdFeriado(Integer idFeriado) {
        this.idFeriado = idFeriado;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getDia() {
        return this.dia;
    }
    
    public void setDia(Date dia) {
        this.dia = dia;
    }

 // GENERADO POR GONZALEZ FERNANDO
    
    public void guardarFeriado(Feriado unFeriado){
        Controlador.getPERSISTENCIA().insert(this);
        //Controlador.getPERSISTENCIA().update(this);

        JOptionPane.showMessageDialog(null,"El Feriado "+ 
                String.valueOf(unFeriado.getIdFeriado()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarFeriado(Feriado unFeriado){
        Controlador.getPERSISTENCIA().update(this);

        JOptionPane.showMessageDialog(null,"El Feriado "+ 
                String.valueOf(unFeriado.getIdFeriado()) +
                " se actualizó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void eliminarFeriado(Feriado unFeriado){
        Controlador.getPERSISTENCIA().delete(this);

        JOptionPane.showMessageDialog(null,"El Feriado "+ 
                String.valueOf(unFeriado.getIdFeriado()) +
                " se elimino correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


