package Clases;
// Generated 13/11/2012 06:11:39 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Inactivo generated by hbm2java
 */
public class Inactivo  implements java.io.Serializable {


     private Integer idInactivo;
     private Nivel nivel;
     private String motivo;
     private Date fechaInicio;
     private Date fechaFin;
     private String instrumentoLegal;

    public Inactivo() {
    }

	
    public Inactivo(Nivel nivel, String motivo, Date fechaInicio, Date fechaFin) {
        this.nivel = nivel;
        this.motivo = motivo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public Inactivo(Nivel nivel, String motivo, Date fechaInicio, Date fechaFin, String instrumentoLegal) {
       this.nivel = nivel;
       this.motivo = motivo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.instrumentoLegal = instrumentoLegal;
    }
   
    public Integer getIdInactivo() {
        return this.idInactivo;
    }
    
    public void setIdInactivo(Integer idInactivo) {
        this.idInactivo = idInactivo;
    }
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getInstrumentoLegal() {
        return this.instrumentoLegal;
    }
    
    public void setInstrumentoLegal(String instrumentoLegal) {
        this.instrumentoLegal = instrumentoLegal;
    }

// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarInactivo(Inactivo unInactivo){
        Controlador.getPERSISTENCIA().insert(this);

        JOptionPane.showMessageDialog(null,"El Inactivo "+ 
                String.valueOf(unInactivo.getIdInactivo()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }

    public void actualizarInactivo(Inactivo unInactivo){
        Controlador.getPERSISTENCIA().update(this);

        JOptionPane.showMessageDialog(null,"El Inactivo "+ 
                String.valueOf(unInactivo.getIdInactivo()) +
                " se actualizó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void eliminarInactivo(Inactivo unInactivo){
        Controlador.getPERSISTENCIA().delete(this);

        JOptionPane.showMessageDialog(null,"El Inactivo "+ 
                String.valueOf(unInactivo.getIdInactivo()) +
                " se eliminó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }

}


