package Clases;
// Generated 17/12/2012 17:24:14 by Hibernate Tools 3.2.1.GA

import javax.swing.JOptionPane;




/**
 * Justificacion generated by hbm2java
 */
public class Justificacion  implements java.io.Serializable {


     private Integer idJustificacion;
     private Asistencia asistencia;
     private Articulo articulo;
     private String motivo;

    public Justificacion() {
    }

	
    public Justificacion(Asistencia asistencia, Articulo articulo) {
        this.asistencia = asistencia;
        this.articulo = articulo;
    }
    public Justificacion(Asistencia asistencia, Articulo articulo, String motivo) {
       this.asistencia = asistencia;
       this.articulo = articulo;
       this.motivo = motivo;
    }
   
    public Integer getIdJustificacion() {
        return this.idJustificacion;
    }
    
    public void setIdJustificacion(Integer idJustificacion) {
        this.idJustificacion = idJustificacion;
    }
    public Asistencia getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Asistencia asistencia) {
        this.asistencia = asistencia;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    public void guardarJustificacion(Justificacion unaJustificacion){
        Controlador.getPERSISTENCIA().insert(this);

        JOptionPane.showMessageDialog(null,"La Justificacion "+ 
                String.valueOf(unaJustificacion.getIdJustificacion()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarJustificacion(Justificacion unaJustificacion){
        Controlador.getPERSISTENCIA().update2(this);

        JOptionPane.showMessageDialog(null,"La Justificacion "+ 
                String.valueOf(unaJustificacion.getIdJustificacion()) +
                " se actualizo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }



}


