package Clases;
// Generated 17/10/2012 08:54:15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Mes generated by hbm2java
 */
public class Mes  implements java.io.Serializable {


     private Integer idMes;
     private Ano ano;
     private Integer mes;
     private Set<Dia> dias = new HashSet<Dia>(0);

    public Mes() {
    }

	
    public Mes(Ano ano) {
        this.ano = ano;
    }
    public Mes(Ano ano, Integer mes, Set<Dia> dias) {
       this.ano = ano;
       this.mes = mes;
       this.dias = dias;
    }
   
    public Integer getIdMes() {
        return this.idMes;
    }
    
    public void setIdMes(Integer idMes) {
        this.idMes = idMes;
    }
    public Ano getAno() {
        return this.ano;
    }
    
    public void setAno(Ano ano) {
        this.ano = ano;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Set<Dia> getDias() {
        return this.dias;
    }
    
    public void setDias(Set<Dia> dias) {
        this.dias = dias;
    }


//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarMes(Mes unMes){
        Controlador.getPERSISTENCIA().insert(this);

        JOptionPane.showMessageDialog(null,"El Mes "+ 
                String.valueOf(unMes.getMes()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public Dia getDia(int dia){
          Dia tmpres=null;
          Iterator it=dias.iterator();
           while(it.hasNext()){
           Dia an=(Dia) it.next();
           if(an.getDia()==dia){
               tmpres=an;
               break;
           }
         }
         return tmpres;
     }
//    
//    public Dia crearDia(Mes mes, Integer dia, Set<Iniciofin> iniciofins){
//        Dia unDia=new Dia(mes, dia, iniciofins);
//        if(!existeDia(unDia)){
//            unDia.guardarDia(unDia);
//        } 
//        return unDia;
//     }

}


