package Clases;
// Generated 01/11/2012 19:46:51 by Hibernate Tools 3.2.1.GA

import javax.swing.JOptionPane;




/**
 * PersonalFamiliar generated by hbm2java
 */
public class PersonalFamiliar  implements java.io.Serializable {


     private PersonalFamiliarId id;
     private Personal personalByIdPersonal;
     private Personal personalByIdFamiliar;
     private Tiporelacion tiporelacion;
     private Boolean asignacionFamiliar;

    public PersonalFamiliar() {
    }

	
    public PersonalFamiliar(PersonalFamiliarId id, Personal personalByIdPersonal, Personal personalByIdFamiliar, Tiporelacion tiporelacion) {
        this.id = id;
        this.personalByIdPersonal = personalByIdPersonal;
        this.personalByIdFamiliar = personalByIdFamiliar;
        this.tiporelacion = tiporelacion;
    }
    public PersonalFamiliar(PersonalFamiliarId id, Personal personalByIdPersonal, Personal personalByIdFamiliar, Tiporelacion tiporelacion, Boolean asignacionFamiliar) {
       this.id = id;
       this.personalByIdPersonal = personalByIdPersonal;
       this.personalByIdFamiliar = personalByIdFamiliar;
       this.tiporelacion = tiporelacion;
       this.asignacionFamiliar = asignacionFamiliar;
    }
    
    @Override
    public String toString() {
        return personalByIdFamiliar.getApellido()+", "+personalByIdFamiliar.getNombre();
    }
   
    public PersonalFamiliarId getId() {
        return this.id;
    }
    
    public void setId(PersonalFamiliarId id) {
        this.id = id;
    }
    public Personal getPersonalByIdPersonal() {
        return this.personalByIdPersonal;
    }
    
    public void setPersonalByIdPersonal(Personal personalByIdPersonal) {
        this.personalByIdPersonal = personalByIdPersonal;
    }
    public Personal getPersonalByIdFamiliar() {
        return this.personalByIdFamiliar;
    }
    
    public void setPersonalByIdFamiliar(Personal personalByIdFamiliar) {
        this.personalByIdFamiliar = personalByIdFamiliar;
    }
    public Tiporelacion getTiporelacion() {
        return this.tiporelacion;
    }
    
    public void setTiporelacion(Tiporelacion tiporelacion) {
        this.tiporelacion = tiporelacion;
    }
    public Boolean getAsignacionFamiliar() {
        return this.asignacionFamiliar;
    }
    
    public void setAsignacionFamiliar(Boolean asignacionFamiliar) {
        this.asignacionFamiliar = asignacionFamiliar;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    public void guardarPersonalFamiliar(PersonalFamiliar unPersonalFamiliar){
        Controlador.getPERSISTENCIA().insert(this);
        //Controlador.getPERSISTENCIA().update(this);

//        JOptionPane.showMessageDialog(null,"El Personal_Familiar "+ 
//                String.valueOf(unPersonalFamiliar.getId().getIdFamiliar()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarPersonalFamiliar(PersonalFamiliar unPersonalFamiliar){
        Controlador.getPERSISTENCIA().update(this);

//        JOptionPane.showMessageDialog(null,"El personal_Familiar "+ 
//                String.valueOf(unPersonalFamiliar.getId().getIdFamiliar()) +
//                " se actualizó correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


