package Clases;
// Generated 04/09/2012 11:32:15 by Hibernate Tools 3.2.1.GA



/**
 * PersonalDocentes generated by hbm2java
 */
public class PersonalDocentes  implements java.io.Serializable {


     private String nroRegistro;
     private Personales personales;
     private String idDocente;
     private String sitRevista;
     private Integer cargoHoras;

    public PersonalDocentes() {
    }

	
    public PersonalDocentes(String nroRegistro, Personales personales, String idDocente) {
        this.nroRegistro = nroRegistro;
        this.personales = personales;
        this.idDocente = idDocente;
    }
    public PersonalDocentes(String nroRegistro, Personales personales, String idDocente, String sitRevista, Integer cargoHoras) {
       this.nroRegistro = nroRegistro;
       this.personales = personales;
       this.idDocente = idDocente;
       this.sitRevista = sitRevista;
       this.cargoHoras = cargoHoras;
    }
   
    public String getNroRegistro() {
        return this.nroRegistro;
    }
    
    public void setNroRegistro(String nroRegistro) {
        this.nroRegistro = nroRegistro;
    }
    public Personales getPersonales() {
        return this.personales;
    }
    
    public void setPersonales(Personales personales) {
        this.personales = personales;
    }
    public String getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(String idDocente) {
        this.idDocente = idDocente;
    }
    public String getSitRevista() {
        return this.sitRevista;
    }
    
    public void setSitRevista(String sitRevista) {
        this.sitRevista = sitRevista;
    }
    public Integer getCargoHoras() {
        return this.cargoHoras;
    }
    
    public void setCargoHoras(Integer cargoHoras) {
        this.cargoHoras = cargoHoras;
    }




}


