package Clases;
// Generated 04/09/2012 11:32:15 by Hibernate Tools 3.2.1.GA



/**
 * PersonalMaestranzas generated by hbm2java
 */
public class PersonalMaestranzas  implements java.io.Serializable {


     private String nroRegistro;
     private Personales personales;
     private String idMaestranza;
     private String tipodeactividad;

    public PersonalMaestranzas() {
    }

	
    public PersonalMaestranzas(String nroRegistro, Personales personales, String idMaestranza) {
        this.nroRegistro = nroRegistro;
        this.personales = personales;
        this.idMaestranza = idMaestranza;
    }
    public PersonalMaestranzas(String nroRegistro, Personales personales, String idMaestranza, String tipodeactividad) {
       this.nroRegistro = nroRegistro;
       this.personales = personales;
       this.idMaestranza = idMaestranza;
       this.tipodeactividad = tipodeactividad;
    }
   
    public String getNroRegistro() {
        return this.nroRegistro;
    }
    
    public void setNroRegistro(String nroRegistro) {
        this.nroRegistro = nroRegistro;
    }
    public Personales getPersonales() {
        return this.personales;
    }
    
    public void setPersonales(Personales personales) {
        this.personales = personales;
    }
    public String getIdMaestranza() {
        return this.idMaestranza;
    }
    
    public void setIdMaestranza(String idMaestranza) {
        this.idMaestranza = idMaestranza;
    }
    public String getTipodeactividad() {
        return this.tipodeactividad;
    }
    
    public void setTipodeactividad(String tipodeactividad) {
        this.tipodeactividad = tipodeactividad;
    }




}


