package Clases;
// Generated 23/02/2013 16:02:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Registroacceso generated by hbm2java
 */
public class Registroacceso  implements java.io.Serializable {


     private Integer idRegistroacceso;
     private Personal personal;
     private Date fecha;
     private Date inicio;
     private Date fin;

    public Registroacceso() {
    }

	
    public Registroacceso(Personal personal) {
        this.personal = personal;
    }
    public Registroacceso(Personal personal, Date fecha, Date inicio, Date fin) {
       this.personal = personal;
       this.fecha = fecha;
       this.inicio = inicio;
       this.fin = fin;
    }
   
    public Integer getIdRegistroacceso() {
        return this.idRegistroacceso;
    }
    
    public void setIdRegistroacceso(Integer idRegistroacceso) {
        this.idRegistroacceso = idRegistroacceso;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Date getFin() {
        return this.fin;
    }
    
    public void setFin(Date fin) {
        this.fin = fin;
    }

/// GENERADO POR GONZALEZ FERNANDO
    
    
    public int guardarRegistroAcceso(Registroacceso unRegistroacceso){
        Controlador.getPERSISTENCIA().insert(this);
        int aux=0;
        aux=unRegistroacceso.getIdRegistroacceso();
        return aux;
//        JOptionPane.showMessageDialog(null,"La Situación de Revista "+ 
//                String.valueOf(unRegistroacceso.getIdRevista()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarRegistroAcceso(Registroacceso unRegistroacceso){
        Controlador.getPERSISTENCIA().update(this);
        
//        return unRegistroacceso.getIdRegistroacceso();
//        JOptionPane.showMessageDialog(null,"La Situación de Revista "+ 
//                String.valueOf(unRegistroacceso.getIdRevista()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }

//    public int Obtenersesion(int id){
//        
//    }

}


