package Clases;
// Generated 02-may-2013 17:40:38 by Hibernate Tools 3.2.1.GA



/**
 * Tareaextracurricular generated by hbm2java
 */
public class Tareaextracurricular  implements java.io.Serializable {


     private TareaextracurricularId id;
     private Tarea tarea;
     private String comentario;

    public Tareaextracurricular() {
    }

	
    public Tareaextracurricular(TareaextracurricularId id, Tarea tarea) {
        this.id = id;
        this.tarea = tarea;
    }
    public Tareaextracurricular(TareaextracurricularId id, Tarea tarea, String comentario) {
       this.id = id;
       this.tarea = tarea;
       this.comentario = comentario;
    }
    
//    @Override
//    public String toString() {
//        return tarea.getNombre();
//    }
   
    public TareaextracurricularId getId() {
        return this.id;
    }
    
    public void setId(TareaextracurricularId id) {
        this.id = id;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarTareaextracurricular(Tareaextracurricular unaTareaextracurricular){
        Controlador.getPERSISTENCIA().insert(this);

//        JOptionPane.showMessageDialog(null,"La Tarea extracurricular "+ 
//                String.valueOf(unaTareaextracurricular.getId()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void actualizarTareaextracurricular(Tareaextracurricular unaTareaextracurricular){
        Controlador.getPERSISTENCIA().update(this);

//        JOptionPane.showMessageDialog(null,"La Tarea extracurricular "+ 
//                String.valueOf(unaTareaextracurricular.getId()) +
//                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


