package Clases;
// Generated 04/09/2012 11:32:15 by Hibernate Tools 3.2.1.GA



/**
 * TareaReuniones generated by hbm2java
 */
public class TareaReuniones  implements java.io.Serializable {


     private int nroTarea;
     private Tareas tareas;
     private String idTareaReunion;
     private String departamento;
     private String organizadopor;

    public TareaReuniones() {
    }

	
    public TareaReuniones(int nroTarea, Tareas tareas, String idTareaReunion) {
        this.nroTarea = nroTarea;
        this.tareas = tareas;
        this.idTareaReunion = idTareaReunion;
    }
    public TareaReuniones(int nroTarea, Tareas tareas, String idTareaReunion, String departamento, String organizadopor) {
       this.nroTarea = nroTarea;
       this.tareas = tareas;
       this.idTareaReunion = idTareaReunion;
       this.departamento = departamento;
       this.organizadopor = organizadopor;
    }
   
    public int getNroTarea() {
        return this.nroTarea;
    }
    
    public void setNroTarea(int nroTarea) {
        this.nroTarea = nroTarea;
    }
    public Tareas getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Tareas tareas) {
        this.tareas = tareas;
    }
    public String getIdTareaReunion() {
        return this.idTareaReunion;
    }
    
    public void setIdTareaReunion(String idTareaReunion) {
        this.idTareaReunion = idTareaReunion;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getOrganizadopor() {
        return this.organizadopor;
    }
    
    public void setOrganizadopor(String organizadopor) {
        this.organizadopor = organizadopor;
    }




}


