package Clases;
// Generated 04/09/2012 11:32:15 by Hibernate Tools 3.2.1.GA



/**
 * TareaAdministrativas generated by hbm2java
 */
public class TareaAdministrativas  implements java.io.Serializable {


     private int nroTarea;
     private Tareas tareas;
     private String idTareaAdm;
     private String tipodetarea;
     private String estado;

    public TareaAdministrativas() {
    }

	
    public TareaAdministrativas(int nroTarea, Tareas tareas, String idTareaAdm) {
        this.nroTarea = nroTarea;
        this.tareas = tareas;
        this.idTareaAdm = idTareaAdm;
    }
    public TareaAdministrativas(int nroTarea, Tareas tareas, String idTareaAdm, String tipodetarea, String estado) {
       this.nroTarea = nroTarea;
       this.tareas = tareas;
       this.idTareaAdm = idTareaAdm;
       this.tipodetarea = tipodetarea;
       this.estado = estado;
    }
   
    public int getNroTarea() {
        return this.nroTarea;
    }
    
    public void setNroTarea(int nroTarea) {
        this.nroTarea = nroTarea;
    }
    public Tareas getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Tareas tareas) {
        this.tareas = tareas;
    }
    public String getIdTareaAdm() {
        return this.idTareaAdm;
    }
    
    public void setIdTareaAdm(String idTareaAdm) {
        this.idTareaAdm = idTareaAdm;
    }
    public String getTipodetarea() {
        return this.tipodetarea;
    }
    
    public void setTipodetarea(String tipodetarea) {
        this.tipodetarea = tipodetarea;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


