package Clases;
// Generated 04/12/2012 09:56:40 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.swing.JOptionPane;

/**
 * Tareaextracurricular generated by hbm2java
 */
public class Tareaextracurricular  implements java.io.Serializable {


     private TareaextracurricularId id;
     private Tarea tarea;
     private Date diaInicio;
     private Date diaFin;

    public Tareaextracurricular() {
    }

	
    public Tareaextracurricular(TareaextracurricularId id, Tarea tarea) {
        this.id = id;
        this.tarea = tarea;
    }
    public Tareaextracurricular(TareaextracurricularId id, Tarea tarea, Date diaInicio, Date diaFin) {
       this.id = id;
       this.tarea = tarea;
       this.diaInicio = diaInicio;
       this.diaFin = diaFin;
    }
   
    public TareaextracurricularId getId() {
        return this.id;
    }
    
    public void setId(TareaextracurricularId id) {
        this.id = id;
    }
    public Tarea getTarea() {
        return this.tarea;
    }
    
    public void setTarea(Tarea tarea) {
        this.tarea = tarea;
    }
    public Date getDiaInicio() {
        return this.diaInicio;
    }
    
    public void setDiaInicio(Date diaInicio) {
        this.diaInicio = diaInicio;
    }
    public Date getDiaFin() {
        return this.diaFin;
    }
    
    public void setDiaFin(Date diaFin) {
        this.diaFin = diaFin;
    }

//// GENERADO POR GONZALEZ FERNANDO
    
    
    public void guardarTareaextracurricular(Tareaextracurricular unaTareaextracurricular){
        Controlador.getPERSISTENCIA().insert(this);

        JOptionPane.showMessageDialog(null,"La Tarea extracurricular "+ 
                String.valueOf(unaTareaextracurricular.getId()) +
                " se guardo correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }


}


