package Clases;
// Generated 04/09/2012 11:32:15 by Hibernate Tools 3.2.1.GA



/**
 * TareaClases generated by hbm2java
 */
public class TareaClases  implements java.io.Serializable {


     private int nroTarea;
     private Tareas tareas;
     private String idTareaClase;
     private String departamento;

    public TareaClases() {
    }

	
    public TareaClases(int nroTarea, Tareas tareas, String idTareaClase) {
        this.nroTarea = nroTarea;
        this.tareas = tareas;
        this.idTareaClase = idTareaClase;
    }
    public TareaClases(int nroTarea, Tareas tareas, String idTareaClase, String departamento) {
       this.nroTarea = nroTarea;
       this.tareas = tareas;
       this.idTareaClase = idTareaClase;
       this.departamento = departamento;
    }
   
    public int getNroTarea() {
        return this.nroTarea;
    }
    
    public void setNroTarea(int nroTarea) {
        this.nroTarea = nroTarea;
    }
    public Tareas getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Tareas tareas) {
        this.tareas = tareas;
    }
    public String getIdTareaClase() {
        return this.idTareaClase;
    }
    
    public void setIdTareaClase(String idTareaClase) {
        this.idTareaClase = idTareaClase;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }




}


