package Clases;
// Generated 19/11/2012 14:01:36 by Hibernate Tools 3.2.1.GA


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 * Tarea generated by hbm2java
 */
public class Tarea  implements java.io.Serializable {


     private Integer idTarea;
     private Establecimiento establecimiento;
     private String nombre;
     private String lugar;
     private String comentario;
     private Boolean estado;
     private Set<Tareareunion> tareareunions = new HashSet<Tareareunion>(0);
     private Set<Agenda> agendas = new HashSet<Agenda>(0);
     private Set<Tareaotro> tareaotros = new HashSet<Tareaotro>(0);
     private Set<Tareaextracurricular> tareaextracurriculars = new HashSet<Tareaextracurricular>(0);
     private Set<Tareaclase> tareaclases = new HashSet<Tareaclase>(0);

    public Tarea() {
    }

	
    public Tarea(Establecimiento establecimiento, String nombre) {
        this.establecimiento = establecimiento;
        this.nombre = nombre;
    }
    public Tarea(Establecimiento establecimiento, String nombre, String lugar, String comentario, Boolean estado, Set<Tareareunion> tareareunions, Set<Agenda> agendas, Set<Tareaotro> tareaotros, Set<Tareaextracurricular> tareaextracurriculars, Set<Tareaclase> tareaclases) {
       this.establecimiento = establecimiento;
       this.nombre = nombre;
       this.lugar = lugar;
       this.comentario = comentario;
       this.estado = estado;
       this.tareareunions = tareareunions;
       this.agendas = agendas;
       this.tareaotros = tareaotros;
       this.tareaextracurriculars = tareaextracurriculars;
       this.tareaclases = tareaclases;
    }
    
    @Override
    public String toString() {
        return nombre;
    }
   
    public Integer getIdTarea() {
        return this.idTarea;
    }
    
    public void setIdTarea(Integer idTarea) {
        this.idTarea = idTarea;
    }
    public Establecimiento getEstablecimiento() {
        return this.establecimiento;
    }
    
    public void setEstablecimiento(Establecimiento establecimiento) {
        this.establecimiento = establecimiento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Tareareunion> getTareareunions() {
        return this.tareareunions;
    }
    
    public void setTareareunions(Set<Tareareunion> tareareunions) {
        this.tareareunions = tareareunions;
    }
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }
    public Set<Tareaotro> getTareaotros() {
        return this.tareaotros;
    }
    
    public void setTareaotros(Set<Tareaotro> tareaotros) {
        this.tareaotros = tareaotros;
    }
    public Set<Tareaextracurricular> getTareaextracurriculars() {
        return this.tareaextracurriculars;
    }
    
    public void setTareaextracurriculars(Set<Tareaextracurricular> tareaextracurriculars) {
        this.tareaextracurriculars = tareaextracurriculars;
    }
    public Set<Tareaclase> getTareaclases() {
        return this.tareaclases;
    }
    
    public void setTareaclases(Set<Tareaclase> tareaclases) {
        this.tareaclases = tareaclases;
    }

//// GENERADO POR GONZALEZ FERNANDO
       
    public int guardarTarea(Tarea unaTarea){
    Controlador.getPERSISTENCIA().insert(this);
    int id=unaTarea.getIdTarea();
    JOptionPane.showMessageDialog(null,"La tarea se guardó correctamente","Registrar tarea",JOptionPane.INFORMATION_MESSAGE);
    return id;
    }
    
    public void ActualizarTarea(Tarea unaTarea){
    Controlador.getPERSISTENCIA().update(this);

    JOptionPane.showMessageDialog(null,"La tarea se actualizó correctamente","Actualizar tarea",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void crearTareaclase(TareaclaseId id, Tarea tarea, String aula, Integer numero){
        Tareaclase unaTareaclase=new Tareaclase(id,tarea,aula,numero);
            unaTareaclase.guardarTareaclase(unaTareaclase);
     }
    
    public void crearTareareunion(TareareunionId id, Tarea tarea, String motivo, String caracter){
        Tareareunion unaTareareunion=new Tareareunion(id,tarea,motivo,caracter);
            unaTareareunion.guardarTareareunion(unaTareareunion);
     }
    
    public void crearTareaextracurricular(TareaextracurricularId id, Tarea tarea, Date diaInicio, Date diaFin){
        Tareaextracurricular unaTareaextracurricular=new Tareaextracurricular(id,tarea,diaInicio,diaFin);
            unaTareaextracurricular.guardarTareaextracurricular(unaTareaextracurricular);
     }
    
    public void crearTareaotro(TareaotroId id, Tarea tarea, String caracteristica, Date diaInicio, Date diaFin){
        Tareaotro unaTareaotro=new Tareaotro(id,tarea,caracteristica,diaInicio,diaFin);
            unaTareaotro.guardarTareaotro(unaTareaotro);
     }
    
    public List ObtenerListaDias(){
        List lista = new ArrayList();
        Date aux=new Date();
        Iterator it=agendas.iterator();
        while(it.hasNext()){
            Agenda age=(Agenda) it.next();
            Iterator ita=age.getAnos().iterator();
            while(ita.hasNext()){
                Ano an=(Ano) ita.next();
                    Iterator itm=an.getMeses().iterator();
                    while(itm.hasNext()){
                        Mes me=(Mes) itm.next();
                        aux.setMonth(me.getMes());
                        Iterator itd=me.getDias().iterator();
                        while(itd.hasNext()){
                            Dia di=(Dia) itd.next();
                            aux.setDate(di.getDia());
                            int d=aux.getDay();
                            if(!lista.contains(d)){
                               lista.add(d);
                            }
                        }
                    }
            }
            break;
        } 
        return lista;
    }
    
    public Date ObtenerFechaMayor(int anio){
        Date mayor = new Date();
        mayor.setYear(anio-20);
        Date aux=new Date();
        aux.setYear(anio);
        Iterator it=agendas.iterator();
        while(it.hasNext()){
            Agenda age=(Agenda) it.next();
            Iterator ita=age.getAnos().iterator();
            while(ita.hasNext()){
                Ano an=(Ano) ita.next();
                if(an.getAno()==anio+1900){
                    Iterator itm=an.getMeses().iterator();
                    while(itm.hasNext()){
                        Mes me=(Mes) itm.next();
                        aux.setMonth(me.getMes());
                        Iterator itd=me.getDias().iterator();
                        while(itd.hasNext()){
                            Dia di=(Dia) itd.next();
                            aux.setDate(di.getDia());
                            if(aux.compareTo(mayor)>0){
                                mayor.setDate(aux.getDate());
                                mayor.setMonth(aux.getMonth());
                                mayor.setYear(aux.getYear());
                            }
                        }
                    }
                }
            }
            break;
        } 
        return mayor;
    }
    
    public Date ObtenerFechaMenor(int anio){
        Date menor = new Date();
        menor.setYear(anio+20);
        Date aux=new Date();
        aux.setYear(anio);
        Iterator it=agendas.iterator();
        while(it.hasNext()){
            Agenda age=(Agenda) it.next();
            Iterator ita=age.getAnos().iterator();
            while(ita.hasNext()){
                Ano an=(Ano) ita.next();
                if(an.getAno()==anio+1900){
                    Iterator itm=an.getMeses().iterator();
                    while(itm.hasNext()){
                        Mes me=(Mes) itm.next();
                        aux.setMonth(me.getMes());
                        Iterator itd=me.getDias().iterator();
                        while(itd.hasNext()){
                            Dia di=(Dia) itd.next();
                            aux.setDate(di.getDia());
                            if(aux.compareTo(menor)<0){
                                menor.setDate(aux.getDate());
                                menor.setMonth(aux.getMonth());
                                menor.setYear(aux.getYear());
                            }
                        }
                    }
                }
            }
            break;
        } 
        return menor;
    }
    
    public void BorrarTodo() {
        Iterator it = agendas.iterator();
        Date aux=new Date();
        Date hoy=new Date();
        while (it.hasNext()) {
            Agenda age = (Agenda) it.next();
            Iterator ita = age.getAnos().iterator();
            while (ita.hasNext()) {
                Ano an = (Ano) ita.next();
                aux.setYear(an.getAno()-1900);
                Iterator itm = an.getMeses().iterator();
                while (itm.hasNext()) {
                    Mes me = (Mes) itm.next();
                    aux.setMonth(me.getMes());
                    Iterator itd = me.getDias().iterator();
                    while (itd.hasNext()) {
                        Dia di = (Dia) itd.next();
                        aux.setDate(di.getDia());
                        Iterator itin=di.getIniciofins().iterator();
                        while(itin.hasNext()){
                                Iniciofin inic=(Iniciofin) itin.next();
                                if(inic.getInicio()!=null){
                                    aux.setHours(inic.getInicio().getHours());
                                    aux.setMinutes(inic.getInicio().getMinutes());
                                }else{
                                    aux.setHours(inic.getFin().getHours());
                                    aux.setMinutes(inic.getFin().getMinutes());
                                }
                        }
                        if(aux.compareTo(hoy)>=0){
                            Iterator iti=di.getIniciofins().iterator();
                            while(iti.hasNext()){
                                Iniciofin ini=(Iniciofin) iti.next();
                                //Asistencia asi=new Asistencia();
                                if (ini.getAsistencias().iterator().hasNext()) {
                                    Asistencia asi = ini.getAsistencias().iterator().next();
                                    Iterator<Justificacion> jus = asi.getJustificacions().iterator();
                                    //Justificacion just;
                                    while (jus.hasNext()) {
                                        Justificacion just = (Justificacion) jus.next();
                                        just.eliminarJustificacion(just);
                                    }
                                    asi.eliminarAsistencia(asi);
                                }
                                ini.eliminarIniciofin(ini);
                                di.eliminarDia(di);
                            }
                        }
                    }
                    if(!Controlador.getPERSISTENCIA().getDias(me.getIdMes()).iterator().hasNext()){
                        me.eliminarMes(me);
                    }
                }
                if(!Controlador.getPERSISTENCIA().getMeses(an.getIdAno()).iterator().hasNext()){
                    an.eliminarAno(an);
                }
            }
            Iterator itf=age.getFrancos().iterator();
            if(itf.hasNext()){
                Franco fran=(Franco)itf.next();
                fran.eliminarFranco(fran);
            }
            if(!Controlador.getPERSISTENCIA().getAnos(age.getId().getIdPersonal(), age.getId().getIdTarea()).iterator().hasNext()){
                age.eliminarAgenda(age);
            }
        }
    }
    
    public Agenda ObtenerAgenda(int idper, int idrev) {
        Agenda age = new Agenda();
        Iterator it=agendas.iterator();
        while(it.hasNext()){
            Agenda ag=(Agenda) it.next();
            if(ag.getId().getIdPersonal()==idper && ag.getRevista().getIdRevista()==idrev){
                age=ag;
                break;
            }
        }
        return age;
    }
    
    public void RecuperarAsistencia(Tarea tar, Date dinicio) {
        try {
            if (tar.getTareaextracurriculars().iterator().hasNext()) {
                Tareaextracurricular tarex = tar.getTareaextracurriculars().iterator().next();
                Date diaini = tarex.getDiaInicio();
                Date diafin = tarex.getDiaFin();
                Iterator it = Controlador.PERSISTENCIA.getAgendas().iterator();
                while (it.hasNext()) {
                    Agenda age = (Agenda) it.next();
                    if (age.getPersonal().getEstado() == true && age.getTarea().getEstado() == true) {
                        if (age.getTarea().getTareaclases().iterator().hasNext()) {
                            if (diaini.getYear() == diafin.getYear() && diaini.getMonth() == diafin.getMonth() && diaini.getDate() == diafin.getDate()) {
                                Date diaaux = diaini;
                                Dia di = age.getDia2(diaaux);
                                if (di.getIdDia() != null) {
                                    Iterator itin = di.getIniciofins().iterator();
                                    while (itin.hasNext()) {
                                        Iniciofin in = (Iniciofin) itin.next();
                                        SimpleDateFormat formateador = new SimpleDateFormat("HH:mm");
                                        String i = formateador.format(in.getInicio());
                                        String ii = formateador.format(in.getFin());
                                        Date inicio = formateador.parse(i);
                                        Date fin = formateador.parse(ii);
                                        String e = formateador.format(diaini);
                                        String ee = formateador.format(diafin);
                                        Date hini = formateador.parse(e);
                                        Date hfin = formateador.parse(ee);
//                                        if(hini.compareTo(inicio)<=0 || hini.compareTo(fin)<=0 && hfin.compareTo(inicio)>=0 || hfin.compareTo(fin)>=0){}
                                        if (hini.compareTo(inicio) <= 0 && hfin.compareTo(inicio) >= 0) {
                                            if (in.getEstadoFin() == null) {
                                                //in.setEstadoInicio(false);
                                                in.setEstadoFin(false);
                                                in.actualizarIniciofin(in);
                                            }
                                        } else if (hini.compareTo(fin) <= 0 && hfin.compareTo(fin) >= 0) {
                                            if (in.getEstadoInicio() == null) {
                                                //in.setEstadoInicio(false);
                                                in.setEstadoInicio(false);
                                                in.actualizarIniciofin(in);
                                            }
                                        } else if (hini.compareTo(inicio) >= 0 && hfin.compareTo(inicio) >= 0 && hini.compareTo(fin) <= 0 && hfin.compareTo(fin) <= 0) {
                                            if (in.getEstadoFin() == null || in.getEstadoInicio() == null) {
                                                in.setEstadoInicio(false);
                                                in.setEstadoFin(false);
                                                in.actualizarIniciofin(in);
                                            }
                                        }
                                    }
                                }
                            } else {
                                Date diaaux = diaini;
                                while (diaaux.compareTo(diafin) <= 0) {
                                    Dia di = age.getDia2(diaaux);
                                    if (di.getIdDia() != null) {
                                        Iterator itin = di.getIniciofins().iterator();
                                        while (itin.hasNext()) {
                                            Iniciofin in = (Iniciofin) itin.next();
                                            SimpleDateFormat formateador = new SimpleDateFormat("HH:mm");
                                            String i = formateador.format(in.getInicio());
                                            String ii = formateador.format(in.getFin());
                                            Date hini = formateador.parse(i);
                                            Date hfin = formateador.parse(ii);
                                            String e = formateador.format(diaini);
                                            String ee = formateador.format(in.getFin());
                                            Date inicio = formateador.parse(e);
                                            Date fin = formateador.parse(ee);
                                            if (diaini.getDate() < di.getDia() && diafin.getDate() > di.getDia()) {
                                                if (in.getEstadoFin() == null || in.getEstadoInicio() == null) {
                                                    in.setEstadoInicio(false);
                                                    in.setEstadoFin(false);
                                                    in.actualizarIniciofin(in);
                                                }
                                            } else if (diaini.getDate() == di.getDia()) {
                                                if (hini.compareTo(inicio) <= 0 && hfin.compareTo(inicio) >= 0) {
                                                    if (in.getEstadoFin() == null) {
                                                        //in.setEstadoInicio(false);
                                                        in.setEstadoFin(false);
                                                        in.actualizarIniciofin(in);
                                                    }
                                                } else if (hini.compareTo(inicio) >= 0) {
                                                    if (in.getEstadoFin() == null || in.getEstadoInicio() == null) {
                                                        in.setEstadoInicio(false);
                                                        in.setEstadoFin(false);
                                                        in.actualizarIniciofin(in);
                                                    }
                                                }
                                            } else if (diafin.getDate() == di.getDia()) {
                                                if (hfin.compareTo(fin) >= 0 && hini.compareTo(fin) <= 0) {
                                                    if (in.getEstadoInicio() == null) {
                                                        //in.setEstadoInicio(false);
                                                        in.setEstadoInicio(false);
                                                        in.actualizarIniciofin(in);
                                                    }
                                                } else if (hfin.compareTo(fin) <= 0) {
                                                    if (in.getEstadoFin() == null || in.getEstadoInicio() == null) {
                                                        in.setEstadoInicio(false);
                                                        in.setEstadoFin(false);
                                                        in.actualizarIniciofin(in);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    diaaux = Controlador.sumarFechasDias(diaaux, 1);
                                }
                            }
                        } else if (age.getTarea().getTareareunions().iterator().hasNext()) {
                            if(age.getTarea().getTareareunions().iterator().next().getCaracter().equals("OBLIGATORIO")){
                                Date diaaux=diaini;
                                while (diaaux.compareTo(diafin) <= 0) {
                                    Dia di = age.getDia2(diaaux);
                                    if (di.getIdDia() != null) {
                                        Iterator itin = di.getIniciofins().iterator();
                                        while (itin.hasNext()) {
                                            Iniciofin in = (Iniciofin) itin.next();
                                            SimpleDateFormat formateador = new SimpleDateFormat("HH:mm");
                                            String i = formateador.format(in.getInicio());
                                            String ii = formateador.format(in.getFin());
                                            Date hini = formateador.parse(i);
                                            Date hfin = formateador.parse(ii);
                                            String e = formateador.format(diaini);
                                            String ee = formateador.format(in.getFin());
                                            Date inicio = formateador.parse(e);
                                            Date fin = formateador.parse(ee);
                                            if (diaini.getDate() < di.getDia() && diafin.getDate() > di.getDia()) {
                                                if (in.getEstadoInicio() == null || in.getEstadoFin() == null) {
                                                    in.setEstadoFin(false);
                                                    in.setEstadoInicio(false);
                                                    in.actualizarIniciofin(in);
                                                }
                                            } else if (diaini.getDate() == di.getDia()) {
                                                if (hini.compareTo(inicio) <= 0 && hfin.compareTo(inicio) >= 0) {
                                                    if (in.getEstadoFin() == null) {
                                                        in.setEstadoFin(false);
                                                        in.actualizarIniciofin(in);
                                                    }
                                                } else if (hini.compareTo(inicio) >= 0) {
                                                    if (in.getEstadoInicio()==null) {
                                                        in.setEstadoInicio(false);
                                                        in.actualizarIniciofin(in);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                    diaaux = Controlador.sumarFechasDias(diaaux, 1);
                                }
                            }
                        }
                    }
                }
            } else if (tar.getTareareunions().iterator().hasNext()) {
//                Tareareunion reu=;
                if (tar.getTareareunions().iterator().next().getCaracter().equals("Obligatorio")) {
                    Date diaini = dinicio;
                    Dia dia = tar.getAgendas().iterator().next().getDia2(diaini);
                    Iniciofin inn = dia.getIniciofins().iterator().next();
                    Date inicio = inn.getInicio();
                    Date fin = inn.getFin();
                    Iterator it = Controlador.PERSISTENCIA.getAgendas().iterator();
                    while (it.hasNext()) {
                        Agenda age = (Agenda) it.next();
                        if (age.getPersonal().getEstado() == true && age.getTarea().getEstado() == true) {
                            if (age.getTarea().getTareaclases().iterator().hasNext()) {
                                Dia di = age.getDia2(diaini);
                                if (di.getIdDia() != null) {
                                    Iterator itin = di.getIniciofins().iterator();
                                    while (itin.hasNext()) {
                                        Iniciofin in = (Iniciofin) itin.next();
                                        SimpleDateFormat formateador = new SimpleDateFormat("HH:mm");
                                        String i = formateador.format(in.getInicio());
                                        String ii = formateador.format(in.getFin());
                                        Date hini = formateador.parse(i);
                                        Date hfin = formateador.parse(ii);
                                        if (hini.compareTo(inicio) <= 0 && hfin.compareTo(inicio) >= 0) {
                                            in.setEstadoInicio(false);
                                            in.setEstadoFin(false);
                                            in.actualizarIniciofin(in);
                                        } else if (hini.compareTo(fin) <= 0 && hfin.compareTo(fin) >= 0) {
                                            in.setEstadoInicio(false);
                                            in.setEstadoFin(false);
                                            in.actualizarIniciofin(in);
                                        } else if (hini.compareTo(inicio) >= 0 && hfin.compareTo(inicio) >= 0 && hini.compareTo(fin) <= 0 && hfin.compareTo(fin) <= 0) {
                                            in.setEstadoInicio(false);
                                            in.setEstadoFin(false);
                                            in.actualizarIniciofin(in);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al recuperar las asistencias","Eliminar tarea",JOptionPane.ERROR_MESSAGE);
        }
    }
}


